### PR TITLE
Build for 3.10 is now possible

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I wanted to test it on my "old" environment. It doesn't change much but it might be useful to some people.

### CODE REVIEW

**Comment by mmstick** [comment]
This has actually broken the menu on GTK 3.16+

**Comment by GuillaumeGomez** [comment]
Arf, sorry. From what I see in my changes, it shouldn't since I didn't touch to the glade file and the only difference in code is the macro. Any more information maybe?

**Comment by mmstick** [comment]
The menu is actually not implemented in the glade file but in the source code in `launch()`

**Comment by GuillaumeGomez** [comment]
I don't have gtk 3.16 so I can't really help on this. What do you mean by "it doesn't work"? The application doesn't compile anymore (but travis builds so not this)? When you run, you have gtk warnings?

**Comment by mmstick** [comment]
Travis is using GTK 3.18 so it passes the build. The GTK-rs team provides a repo for installing 3.18 on Trusty so that it can build, at least until Travis is updated to Xenial which is using GTK 3.18.  Which Linux distribution are you using? All the major distributions are shipping at least 3.18 right now, as far as I know (Ubuntu, Fedora, Gentoo, Arch).

As for not working, the menu uses a `PopoverMenu` in the `MenuButton` so that when the `MenuButton` is clicked, the `PopoverMenu` displays a list of buttons to switch the left pane's `Stack` to either services, sockets, or timers. After this change, that `MenuButton` was simply greyed out and no longer clickable.

**Pull request merged**
