### PR TITLE
Notebook2

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
It *should* fix the issues you encountered. If not, can you tell if it works when you remove the `with_gtk_3_16` please?

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
So, have you tested?

**Comment by mmstick** [comment]
This does allow the menubutton to work now, but it does undo a number of recent commits made to the glade and the source code, such as menu button changes.

**Comment by mmstick** [comment]
Okay, with your build, I get this:

```sh
src/systemd/dbus.rs:146:1: 164:2 warning: function is never used: `enable_unit_files`, #[warn(dead_code)] on by default
src/systemd/dbus.rs:146 pub fn enable_unit_files(unit: &str) -> Option<String> {
                        ^
src/systemd/dbus.rs:168:1: 186:2 warning: function is never used: `disable_unit_files`, #[warn(dead_code)] on by default
src/systemd/dbus.rs:168 pub fn disable_unit_files(unit: &str) -> Option<String> {
```

And the MenuButton does not allow clicking.

**Comment by mmstick** [comment]
If I remove `with_gtk_3_16` I get

```
systemd_gui.rs:167:19: 167:31 error: no method named `set_position` found for type `gtk::HeaderBar` in the current scope
systemd_gui.rs:167         right_bar.set_position(1);
                                     ^~~~~~~~~~~~
systemd_gui.rs:167:19: 167:31 note: the method `set_position` exists but the following trait bounds were not satisfied: `gtk::HeaderBar : gtk::IsA<gtk::Editable>`, `gtk::HeaderBar : gtk::IsA<gtk::Window>`, `gtk::HeaderBar : gtk::IsA<gtk::Popover>`
error: aborting due to previous error
```

You can specifiy the position with Glade though.

**Comment by mmstick** [comment]
And if I remove that one line, I just get a panic on a None value:

```
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
stack backtrace:
   1:     0x56465cab0e20 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:     0x56465cab4d6b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:     0x56465cab49f3 - std::panicking::default_hook::hc2c969e7453d080c
   4:     0x56465caa77df - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
   5:     0x56465caa82e8 - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
   6:     0x56465cab01e1 - rust_begin_unwind
   7:     0x56465caeafaf - core::panicking::panic_fmt::h257ceb0aa351d801
   8:     0x56465caeb288 - core::panicking::panic::h4bb1497076d04ab9
   9:     0x56465ca579ad - _<std..option..Option<T>>::unwrap::h6ba146c0d1022871
                        at ../src/libcore/macros.rs:21
  10:     0x56465ca44901 - systemd_manager::systemd_gui::launch::hec754e8cc76f2b1b
                        at /home/mmstick/Programming/testing/systemd-manager/src/systemd_gui.rs:170
  11:     0x56465ca43fe8 - systemd_manager::main::h22a01905651f008f
                        at /home/mmstick/Programming/testing/systemd-manager/src/main.rs:10
  12:     0x56465cab4634 - std::sys_common::unwind::try::try_fn::h04c0c89e4add6cc4
  13:     0x56465cab016b - __rust_try
  14:     0x56465cab407b - std::rt::lang_start::h61f4934e780b4dfc
  15:     0x56465ca474f9 - main
  16:     0x7f3e41a17740 - __libc_start_main
  17:     0x56465ca43ed8 - _start
  18:                0x0 - <unknown>
```

**Comment by GuillaumeGomez** [comment]
With the first version I patched it was possible to use an older version (I fixed the issue). But with the current version, it wouldn't have any sense.

**Pull request closed without merging**
